---
- name: "INCLUDED | Debian & Ubuntu playbook"
  block:
    # Fix: check if snmpd.pid exists
    - name: 'CHECK | does snmpd.pid exist?'
      stat:
        path: /run/snmpd.pid
      register: snmpdpid

    - name: 'DEBIAN UBUNTU | fix wrong snmpd pid preventing snmpd from restarting'
      file:
        path: /run/snmpd.pid
        state: absent
      when: snmpdpid.stat.exists

    - name: 'DEBIAN UBUNTU | recreate correct snmpd.pid'
      shell: "pidof snmpd > /run/snmpd.pid"
      ignore_errors: true
      when: snmpdpid.stat.exists

    - name: 'DEBIAN UBUNTU | apt-get clean'
      command: apt-get clean warn=no
      when: pm_manage_apt_clean

    - name: 'DEBIAN UBUNTU | apt-get autoremove'
      apt: autoremove=yes
      when: pm_manage_apt_autoremove

    - name: 'DEBIAN UBUNTU | apt-get dist-upgrade'
      apt: upgrade=dist update_cache=yes
      register: update_resultat

    - name: 'DEBIAN UBUNTU | Print update result'
      debug: var=update_resultat.stdout_lines
      when:
        - update_resultat is defined
        - update_resultat != ""
        - pm_apt_verbose_package_list|bool

    - name: 'DEBIAN UBUNTU | apt-get autoremove'
      apt: autoremove=yes

  rescue:
    - name: 'DEBIAN UBUNTU | Print update result'
      debug: var=update_resultat.stdout_lines
      when:
        - update_resultat is defined
        - update_resultat != ""

    - name: "DEBIAN UBUNTU | Fail"
      fail:
        msg: "FAIL : something went wrong ..."

  become: true
