---
# Check if a custom tasks file exist for this hostname
- name: "CHECK | Does {{ playbook_dir }}/custom_tasks/before_pm_{{ inventory_hostname_short }}_custom_tasks.yml file exist ?"
  stat:
    path: "{{ playbook_dir }}/custom_tasks/before_pm_{{ inventory_hostname_short }}_custom_tasks.yml"
  register: custom_before
  delegate_to: localhost

# Play this file's tasks if it exists
- name: "INCLUDE | {{ playbook_dir }}/custom_tasks/before_pm_{{ inventory_hostname_short }}_custom_tasks.yml exists"
  include_tasks: "{{ playbook_dir }}/custom_tasks/before_pm_{{ inventory_hostname_short }}_custom_tasks.yml"
  when:
    - custom_before is defined
    - custom_before.stat.exists
