---
# tasks file for patchmanagement
- name: "PLAY | Linux Patch Management Job"
  debug: msg="Start {{ inventory_hostname_short }} patch management"

- name: Gather facts
  setup:
    gather_subset:
      - 'all'

# Everything that should be done before modifying the system
- include_tasks: setup.yml

# Everything you need to do before starting the PM
# eg: sending a notification on mattermost, slack or any other system
- include_tasks: "{{ pm_before_update_tasks_file | default('empty.yml') }}"

# Everything to be done per computer basis
# like stopping services, taking snapshots, etc.
- include_tasks: check_pm_before_update_custom_tasks_file.yml

# Now we do the main job
- include_tasks: patch.yml

# Let's restart the server
- include_tasks: reboot.yml
  when: pm_restart_after_update|bool

# And set some facts
- include_tasks: facts.yml

# Everything to be done per computer basis
# like starting services, flushing caches, etc.
- include_tasks: check_pm_after_update_custom_tasks_file.yml

# Everything you need to do before starting the PM
# eg: sending a notification on mattermost, slack or any other system
- include_tasks: "{{ pm_after_update_tasks_file | default('empty.yml') }}"
