---
# Reboot the target after the update
- name: "REBOOT | Reboot triggered"
  reboot:
    msg: "Reboot initiated by Ansible. Related to Patch Management."
    reboot_timeout: 600
    test_command: "whoami"
    post_reboot_delay: 15
  changed_when: false
  become: true
  become_user: "root"
  tags: molecule-notest

- name: "CHECK | Ensure we are not in rescue mode"
  wait_for_connection:
    timeout: 120
