---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centostest
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: ubuntutest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
